# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa89395dad24de888c178625baf8e04095610eccc8245c451794d2d6b03ccdc10494eb8526e18e474858e3f954d3832d6d99b65a5fac319960903256778ab77e

test:
  secret_key_base: 8dabc4e08f38519d384d10152a75b8fef775023dad8b443bcf7825bb55aa8d452aad098f8bb5732b219961a7748105a7dba750cd4e82db40c3aecbe7222e1927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
